# Use the official Node.js image from Docker Hub
FROM node:alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Expose the port your application is listening on (if applicable)
# EXPOSE 3000

# Start the application in the background
CMD ["npm", "start"]
